ALTER TABLE public.daily_performance
ADD COLUMN IF NOT EXISTS signals_considered INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS signals_generated INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS trades_executed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS trades_failed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS trades_pending INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS automation_level TEXT DEFAULT 'guided',
ADD COLUMN IF NOT EXISTS operator_ran_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS execution_details JSONB DEFAULT '[]'::jsonb;