ALTER TABLE public.user_settings
  ADD COLUMN IF NOT EXISTS min_score NUMERIC DEFAULT 60,
  ADD COLUMN IF NOT EXISTS min_r NUMERIC DEFAULT 1.5,
  ADD COLUMN IF NOT EXISTS min_confidence NUMERIC DEFAULT 55;